#!/usr/bin/env python
# coding: utf-8
1. What is your definition of clustering? What are a few clustering algorithms you might think of?
2. What are some of the most popular clustering algorithm applications?
3. When using K-Means, describe two strategies for selecting the appropriate number of clusters.

4. What is mark propagation and how does it work? Why would you do it, and how would you do it?

5. Provide two examples of clustering algorithms that can handle large datasets. And two that look for high-density areas?

6. Can you think of a scenario in which constructive learning will be advantageous? How can you go about putting it into action?

7. How do you tell the difference between anomaly and novelty detection?

8. What is a Gaussian mixture, and how does it work? What are some of the things you can do about it?

9. When using a Gaussian mixture model, can you name two techniques for determining the correct number of clusters?
1. What is your definition of clustering? What are a few clustering algorithms you might think of?

Sol: Clustering: Clusting is the process of macking the group of the data with similar features. EX: K-Menas Klustring, KNN, 

Centroid-based clustering organizes the data into non-hierarchical clusters, in contrast to hierarchical clustering defined below. k-means is the most widely-used centroid-based clustering algorithm. Centroid-based algorithms are efficient but sensitive to initial conditions and outliers.Q. 2. What are some of the most popular clustering algorithm applications?
Sol:Image processing, data analysis, pattern recognition, market research and many moreQ. 3. When using K-Means, describe two strategies for selecting the appropriate number of clusters.
SOL: 1. By using elbow method:Perform K-means clustering with all these different values of K. For each of the K values, we calculate average distances to the centroid across all data points.
Plot these points and find the point where the average distance from the centroid falls suddenly
2. Silhouette analysis
The silhouette coefficient is a measure of how similar a data point is within-cluster (cohesion) compared to other clusters (separation).Q. 4.What is mark propagation and how does it work? Why would you do it, and how would you do it?5. Provide two examples of clustering algorithms that can handle large datasets. And two that look for high-density areas?

Sol: Online K-Means & K Means clustering. DBSCAN clustering  algorithms look for high-density areas. 6. Can you think of a scenario in which constructive learning will be advantageous? How can you go about putting it into action?
Sol: 7. How do you tell the difference between anomaly and novelty detection?
Sol:Outlier = legitimate data point that’s far away from the mean or median in a distribution.
Anomaly = illegitimate data point that’s generated by a different process than whatever generated the rest of the data
Anomaly detection refers to the problem of ending anomalies in data. While anomaly is a generally accepted term, other synonyms, such as outliers are often used in different application domains. In particular, anomalies and outliers are often used interchangeably.

8. What is a Gaussian mixture, and how does it work? What are some of the things you can do about it?

Sol: A Gaussian Mixture is a function that is comprised of several Gaussians, each identified by k ∈ {1,…, K}, where K is the number of clusters of our dataset.A Gaussian mixture model is a probabilistic model that assumes all the data points are generated from a mixture of a finite number of Gaussian distributions with unknown parameters.

# In[ ]:


get_ipython().set_next_input('9. When using a Gaussian mixture model, can you name two techniques for determining the correct number of clusters');get_ipython().run_line_magic('pinfo', 'clusters')
Elbow method is used for finding the optimal number of clusters.

